import path from "path";
import process from "process";
import { pathToFileURL } from "url";
import { compile, loadConfig } from "./commands.js";
import { SymbolTable } from "../symbolTable.js";
import { discoverExports } from "../serve/discovery.js";
import { createMcpHandler, startStdioServer } from "../serve/mcp/adapter.js";
import { startHttpServer } from "../serve/http/adapter.js";
import { createLogger } from "../logger.js";
import { VERSION } from "../version.js";
import type { ExportedItem } from "../serve/types.js";
import * as esbuild from "esbuild";

type CompileResult = {
  outputPath: string;
  moduleId: string;
  exportedNodeNames: string[];
};

function compileForServe(file: string): CompileResult {
  const config = loadConfig();
  const absoluteFile = path.resolve(file);
  const symbolTable = SymbolTable.build(absoluteFile, config);

  const outputPath = compile(config, file, undefined, { symbolTable });
  if (!outputPath) {
    throw new Error(`Compilation failed for ${file}`);
  }

  const fileSymbols = symbolTable.getFile(absoluteFile);
  const exportedNodeNames = Object.values(fileSymbols ?? {})
    .filter((sym) => sym.kind === "node" && sym.exported)
    .map((sym) => sym.name);

  const moduleId = path.relative(process.cwd(), absoluteFile);
  return { outputPath, moduleId, exportedNodeNames };
}

async function loadAndDiscover(
  compileResult: CompileResult,
): Promise<{ exports: ExportedItem[]; moduleExports: Record<string, unknown> }> {
  const moduleUrl = pathToFileURL(path.resolve(compileResult.outputPath)).href;
  const mod = await import(moduleUrl);
  const moduleExports = mod as Record<string, unknown>;

  const toolRegistry =
    (moduleExports.__toolRegistry as Record<string, any>) ?? {};

  const exports = discoverExports({
    toolRegistry,
    moduleExports,
    moduleId: compileResult.moduleId,
    exportedNodeNames: compileResult.exportedNodeNames,
  });

  return { exports, moduleExports };
}

export async function serveMcp(
  file: string,
  options: { name?: string },
): Promise<void> {
  const compileResult = compileForServe(file);
  const { exports } = await loadAndDiscover(compileResult);

  const serverName = options.name ?? path.basename(file, ".agency");
  const handler = createMcpHandler({
    serverName,
    serverVersion: VERSION,
    exports,
  });

  startStdioServer(handler);
}

export async function serveHttp(
  file: string,
  options: { port?: string; apiKey?: string; standalone?: boolean },
): Promise<void> {
  const compileResult = compileForServe(file);

  if (options.standalone) {
    await generateStandalone(compileResult.outputPath, file);
    return;
  }

  const { exports, moduleExports } = await loadAndDiscover(compileResult);
  const port = parseInt(options.port ?? "3000", 10);
  const logger = createLogger("info");

  startHttpServer({
    exports,
    port,
    apiKey: options.apiKey,
    logger,
    hasInterrupts: moduleExports.hasInterrupts as (data: unknown) => boolean,
    respondToInterrupts: moduleExports.respondToInterrupts as (
      interrupts: unknown[],
      responses: unknown[],
    ) => Promise<unknown>,
  });
}

async function generateStandalone(
  compiledPath: string,
  originalFile: string,
): Promise<void> {
  const outfile = path.basename(originalFile, ".agency") + ".server.js";

  await esbuild.build({
    entryPoints: [compiledPath],
    bundle: true,
    platform: "node",
    format: "esm",
    outfile,
    banner: {
      js: "// Generated by Agency — standalone HTTP server\n",
    },
  });

  console.log(`Standalone server written to ${outfile}`);
}
