import { AgencyConfig } from "@/config.js";
import {
  AgencyProgram,
  AgencyNode,
  FunctionDefinition,
  GraphNodeDefinition,
  TypeAlias,
  VariableType,
  ImportStatement,
  ImportNodeStatement,
  ImportToolStatement,
} from "@/types.js";
import { variableTypeToString } from "./typescriptGenerator/typeToString.js";

/**
 * Generates .d.ts declaration files from Agency AST.
 *
 * Produces TypeScript declarations for:
 * - Type aliases
 * - `def` functions (tool-style: args array + metadata)
 * - `node` graph nodes (wrapper-style: named params + options)
 * - Tool definition exports (__nameTool, __nameToolParams)
 * - The default graph export
 * - Import re-exports
 */
export class DeclarationGenerator {
  private program: AgencyProgram;
  private config: AgencyConfig;
  private typeAliases: Record<string, VariableType> = {};
  private lines: string[] = [];

  constructor(program: AgencyProgram, config: AgencyConfig = {}) {
    this.program = program;
    this.config = config;
  }

  generate(): string {
    this.lines = [];
    this.collectTypeAliases();

    this.emitHeader();
    this.emitImports();
    this.emitTypeAliases();
    this.emitReturnObjectType();
    this.emitFunctions();
    this.emitGraphNodes();
    this.emitToolDefinitions();
    this.emitDefaultExport();

    return this.lines.join("\n") + "\n";
  }

  private collectTypeAliases(): void {
    for (const node of this.program.nodes) {
      if (node.type === "typeAlias") {
        this.typeAliases[node.aliasName] = node.aliasedType;
      }
    }
  }

  private emit(line: string = ""): void {
    this.lines.push(line);
  }

  private typeToString(vt: VariableType): string {
    return variableTypeToString(vt, this.typeAliases);
  }

  // --- Header ---

  private emitHeader(): void {
    this.emit("// Auto-generated by Agency compiler");
    this.emit("// Do not edit manually");
    this.emit("");
  }

  // --- Imports ---

  private emitImports(): void {
    let hasImports = false;

    for (const node of this.program.nodes) {
      if (node.type === "importStatement") {
        this.emitImportStatement(node);
        hasImports = true;
      } else if (node.type === "importNodeStatement") {
        this.emitImportNodeStatement(node);
        hasImports = true;
      } else if (node.type === "importToolStatement") {
        this.emitImportToolStatement(node);
        hasImports = true;
      }
    }

    if (hasImports) {
      this.emit("");
    }
  }

  private emitImportStatement(node: ImportStatement): void {
    // Re-emit the import with .js extension (already transformed by compile pipeline)
    const parts: string[] = [];
    for (const name of node.importedNames) {
      if (name.type === "defaultImport") {
        parts.push(name.importedNames);
      } else if (name.type === "namedImport") {
        parts.push(`{ ${name.importedNames.join(", ")} }`);
      } else if (name.type === "namespaceImport") {
        parts.push(`* as ${name.importedNames}`);
      }
    }
    const modulePath = node.modulePath.replace(/\.agency$/, ".js");
    this.emit(`import ${parts.join(", ")} from "${modulePath}";`);
  }

  private emitImportNodeStatement(node: ImportNodeStatement): void {
    const modulePath = node.agencyFile.replace(/\.agency$/, ".js");
    this.emit(
      `import { ${node.importedNodes.join(", ")} } from "${modulePath}";`,
    );
  }

  private emitImportToolStatement(node: ImportToolStatement): void {
    const modulePath = node.agencyFile.replace(/\.agency$/, ".js");
    const toolExports = node.importedTools
      .map((t) => `__${t}Tool, __${t}ToolParams`)
      .join(", ");
    this.emit(`import { ${toolExports} } from "${modulePath}";`);
  }

  // --- Type Aliases ---

  private emitTypeAliases(): void {
    const aliases = this.program.nodes.filter(
      (n): n is TypeAlias => n.type === "typeAlias",
    );
    if (aliases.length === 0) return;

    for (const alias of aliases) {
      this.emit(
        `export type ${alias.aliasName} = ${this.typeToString(alias.aliasedType)};`,
      );
    }
    this.emit("");
  }

  // --- ReturnObject type ---

  private emitReturnObjectType(): void {
    const hasNodes = this.program.nodes.some((n) => n.type === "graphNode");
    if (!hasNodes) return;

    this.emit("export interface TokenStats {");
    this.emit("  usage: {");
    this.emit("    inputTokens: number;");
    this.emit("    outputTokens: number;");
    this.emit("    cachedInputTokens: number;");
    this.emit("    totalTokens: number;");
    this.emit("  };");
    this.emit("  cost: {");
    this.emit("    inputCost: number;");
    this.emit("    outputCost: number;");
    this.emit("    totalCost: number;");
    this.emit('    currency: "USD";');
    this.emit("  };");
    this.emit("}");
    this.emit("");
    this.emit("export interface ReturnObject<T = any> {");
    this.emit("  messages: any;");
    this.emit("  data: T;");
    this.emit("  tokens: TokenStats;");
    this.emit("}");
    this.emit("");
    this.emit("export interface NodeOptions {");
    this.emit("  messages?: any[];");
    this.emit("  callbacks?: Record<string, (...args: any[]) => any>;");
    this.emit("}");
    this.emit("");
  }

  // --- `def` functions ---

  private emitFunctions(): void {
    const functions = this.program.nodes.filter(
      (n): n is FunctionDefinition => n.type === "function",
    );
    if (functions.length === 0) return;

    for (const fn of functions) {
      this.emitFunction(fn);
    }
    this.emit("");
  }

  private emitFunction(fn: FunctionDefinition): void {
    const params = fn.parameters.map((p) => {
      const type = p.typeHint ? this.typeToString(p.typeHint) : "any";
      return `${p.name}: ${type}`;
    });
    params.push("__metadata?: Record<string, any>");
    const returnType = fn.returnType
      ? this.typeToString(fn.returnType)
      : "any";

    if (fn.docString) {
      this.emit(`/** ${fn.docString.value.trim()} */`);
    }
    this.emit(
      `export function ${fn.functionName}(${params.join(", ")}): Promise<${returnType}>;`,
    );
  }

  // --- Graph nodes ---

  private emitGraphNodes(): void {
    const nodes = this.program.nodes.filter(
      (n): n is GraphNodeDefinition => n.type === "graphNode",
    );
    if (nodes.length === 0) return;

    for (const node of nodes) {
      this.emitGraphNode(node);
    }
    this.emit("");
  }

  private emitGraphNode(node: GraphNodeDefinition): void {
    // Graph nodes get a public wrapper: export async function name(param1, param2, { messages, callbacks } = {})
    // Returns ReturnObject<T>
    const params = node.parameters.map((p) => {
      const type = p.typeHint ? this.typeToString(p.typeHint) : "any";
      return `${p.name}: ${type}`;
    });
    params.push("options?: NodeOptions");

    const dataType = node.returnType
      ? this.typeToString(node.returnType)
      : "undefined";

    this.emit(
      `export function ${node.nodeName}(${params.join(", ")}): Promise<ReturnObject<${dataType}>>;`,
    );
  }

  // --- Tool definitions ---

  private emitToolDefinitions(): void {
    const functions = this.program.nodes.filter(
      (n): n is FunctionDefinition => n.type === "function",
    );
    if (functions.length === 0) return;

    for (const fn of functions) {
      const paramNames = fn.parameters.map((p) => `"${p.name}"`);
      this.emit("");
      this.emit(`export const __${fn.functionName}Tool: {`);
      this.emit(`  name: "${fn.functionName}";`);
      this.emit("  description: string;");
      this.emit("  schema: import('zod').ZodType;");
      this.emit("};");
      this.emit(
        `export const __${fn.functionName}ToolParams: [${paramNames.join(", ")}];`,
      );
    }
    this.emit("");
  }

  // --- Default export ---

  private emitDefaultExport(): void {
    const hasNodes = this.program.nodes.some((n) => n.type === "graphNode");
    if (!hasNodes) return;

    this.emit("declare const graph: any;");
    this.emit("export default graph;");
  }
}

/**
 * Generate a .d.ts declaration string from an Agency AST.
 */
export function generateDeclarations(
  program: AgencyProgram,
  config: AgencyConfig = {},
): string {
  const generator = new DeclarationGenerator(program, config);
  return generator.generate();
}
