// THIS FILE WAS AUTO-GENERATED
// Source: lib/templates/cli/schedule/githubWorkflow.mustache
// Any manual changes will be lost.
import { apply } from "typestache";

export const template = `# Generated by \`agency schedule add\`. Edit freely.
# Action SHAs are pinned. Re-run \`agency schedule add --force\` after upgrading agency-lang to refresh.
name: {{name:string}}
on:
  schedule:
    - cron: '{{cron:string}}'
  workflow_dispatch:
permissions:
{{{permissionsBlock:string}}}
concurrency:
{{{concurrencyGroup:string}}}
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@{{checkoutRef:string}}
      - uses: egonSchiele/run-agency-action@{{runAgentActionRef:string}}
        with:
          file: {{{agentFile:string}}}
{{{envBlock:string}}}
`;

export type TemplateType = {
  name: string;
  cron: string;
  permissionsBlock: string;
  concurrencyGroup: string;
  checkoutRef: string;
  runAgentActionRef: string;
  agentFile: string;
  envBlock: string;
};

const render = (args: TemplateType) => {
  return apply(template, args);
}

export default render;
    