// Generated by scripts/generate-effect-sets.mjs from stdlib/effectSets.agency.
// Do not edit; run `make` after changing the .agency file.
import type { EffectSetInfo } from "./effectSets.js";

export const BUILTIN_EFFECT_SETS: Record<string, EffectSetInfo> = {
  "FileRead": {
    "name": "FileRead",
    "doc": "Read-only filesystem access: reading files and listing/searching paths.",
    "members": [
      "std::read",
      "std::readBinary",
      "std::ls",
      "std::glob",
      "std::grep",
      "std::vision"
    ],
    "composedOf": []
  },
  "FileWrite": {
    "name": "FileWrite",
    "doc": "Filesystem mutation: creating, editing, moving, copying, and deleting.",
    "members": [
      "std::write",
      "std::writeBinary",
      "std::edit",
      "std::applyPatch",
      "std::mkdir",
      "std::move",
      "std::copy",
      "std::remove",
      "std::cropImage",
      "std::pasteImages"
    ],
    "composedOf": []
  },
  "FileSystem": {
    "name": "FileSystem",
    "doc": "All filesystem access — reads and writes.",
    "members": [
      "std::read",
      "std::readBinary",
      "std::ls",
      "std::glob",
      "std::grep",
      "std::vision",
      "std::write",
      "std::writeBinary",
      "std::edit",
      "std::applyPatch",
      "std::mkdir",
      "std::move",
      "std::copy",
      "std::remove",
      "std::cropImage",
      "std::pasteImages"
    ],
    "composedOf": [
      "FileRead",
      "FileWrite"
    ]
  },
  "Shell": {
    "name": "Shell",
    "doc": "Arbitrary command / process execution. The sharpest edge — grant with care.",
    "members": [
      "std::bash",
      "std::exec",
      "std::run"
    ],
    "composedOf": []
  },
  "Network": {
    "name": "Network",
    "doc": "Anything that talks to the outside world over the network.",
    "members": [
      "std::http::fetch",
      "std::http::fetchJSON",
      "std::http::fetchMarkdown",
      "std::search",
      "std::tavilySearch",
      "std::weather",
      "std::browserUse",
      "std::wikipedia::article",
      "std::wikipedia::search",
      "std::wikipedia::summary",
      "std::gdelt",
      "std::fred",
      "std::dbnomics",
      "std::edgar",
      "std::littlesis",
      "std::yc",
      "std::hackernews",
      "std::bluesky",
      "std::wikidata",
      "std::usaspending",
      "std::aws::s3::get",
      "std::aws::s3::getBinary",
      "std::aws::s3::put",
      "std::aws::s3::putBinary",
      "std::aws::s3::createBucket",
      "std::github::prList",
      "std::github::prGet",
      "std::github::prDiff",
      "std::github::prFiles",
      "std::github::prReviewList",
      "std::github::prReviewCommentList",
      "std::github::prChecks",
      "std::github::issueList",
      "std::github::issueGet",
      "std::github::issueCommentList",
      "std::github::issueSearch",
      "std::github::prReviewComment",
      "std::github::prReview",
      "std::github::prApprove",
      "std::github::issueCreate",
      "std::github::issueComment",
      "std::github::issueUpdate",
      "std::github::issueLabel",
      "std::uploadImage"
    ],
    "composedOf": []
  },
  "AwsS3": {
    "name": "AwsS3",
    "doc": "Amazon S3 access: reading and writing objects, creating buckets, and minting presigned download URLs. Presigning is deliberately NOT in Network — it sends nothing; it mints a bearer capability locally.",
    "members": [
      "std::aws::s3::get",
      "std::aws::s3::getBinary",
      "std::aws::s3::put",
      "std::aws::s3::putBinary",
      "std::aws::s3::createBucket",
      "std::aws::s3::presignGet"
    ],
    "composedOf": []
  },
  "GithubRead": {
    "name": "GithubRead",
    "doc": "Read-only GitHub access: pull requests, issues, and their comments.",
    "members": [
      "std::github::prList",
      "std::github::prGet",
      "std::github::prDiff",
      "std::github::prFiles",
      "std::github::prReviewList",
      "std::github::prReviewCommentList",
      "std::github::prChecks",
      "std::github::issueList",
      "std::github::issueGet",
      "std::github::issueCommentList",
      "std::github::issueSearch"
    ],
    "composedOf": []
  },
  "GithubReview": {
    "name": "GithubReview",
    "doc": "Posting comments and reviews on GitHub pull requests.",
    "members": [
      "std::github::prReviewComment",
      "std::github::prReview",
      "std::github::prApprove"
    ],
    "composedOf": []
  },
  "GithubIssueWrite": {
    "name": "GithubIssueWrite",
    "doc": "Creating and editing GitHub issues.",
    "members": [
      "std::github::issueCreate",
      "std::github::issueComment",
      "std::github::issueUpdate",
      "std::github::issueLabel"
    ],
    "composedOf": []
  },
  "GithubWrite": {
    "name": "GithubWrite",
    "doc": "All GitHub mutations.",
    "members": [
      "std::github::prReviewComment",
      "std::github::prReview",
      "std::github::prApprove",
      "std::github::issueCreate",
      "std::github::issueComment",
      "std::github::issueUpdate",
      "std::github::issueLabel"
    ],
    "composedOf": [
      "GithubReview",
      "GithubIssueWrite"
    ]
  },
  "Github": {
    "name": "Github",
    "doc": "All GitHub access.",
    "members": [
      "std::github::prList",
      "std::github::prGet",
      "std::github::prDiff",
      "std::github::prFiles",
      "std::github::prReviewList",
      "std::github::prReviewCommentList",
      "std::github::prChecks",
      "std::github::issueList",
      "std::github::issueGet",
      "std::github::issueCommentList",
      "std::github::issueSearch",
      "std::github::prReviewComment",
      "std::github::prReview",
      "std::github::prApprove",
      "std::github::issueCreate",
      "std::github::issueComment",
      "std::github::issueUpdate",
      "std::github::issueLabel"
    ],
    "composedOf": [
      "GithubRead",
      "GithubWrite"
    ]
  },
  "DataFinance": {
    "name": "DataFinance",
    "doc": "The std::data/finance connectors (macro + filings). Each also raises\nstd::http::fetchJSON, which is covered by the broader Network set. GDELT\n(news) lives in std::data/news and is not part of this set.",
    "members": [
      "std::fred",
      "std::edgar",
      "std::dbnomics"
    ],
    "composedOf": []
  },
  "Messaging": {
    "name": "Messaging",
    "doc": "Sending messages to people: email, SMS, and iMessage.",
    "members": [
      "std::sendEmail",
      "std::sendSms",
      "std::sendIMessage"
    ],
    "composedOf": []
  },
  "Secrets": {
    "name": "Secrets",
    "doc": "Reading and writing credentials in the system keyring.",
    "members": [
      "std::getSecret",
      "std::setSecret",
      "std::deleteSecret"
    ],
    "composedOf": []
  },
  "Auth": {
    "name": "Auth",
    "doc": "OAuth-style authorization flows: granting, fetching, and revoking access.",
    "members": [
      "std::authorize",
      "std::getAccessToken",
      "std::revokeAuth"
    ],
    "composedOf": []
  },
  "Calendar": {
    "name": "Calendar",
    "doc": "Calendar access: listing and mutating events (incl. calendar authorization).",
    "members": [
      "std::listEvents",
      "std::createEvent",
      "std::updateEvent",
      "std::deleteEvent",
      "std::authorizeCalendar"
    ],
    "composedOf": []
  },
  "Memory": {
    "name": "Memory",
    "doc": "Agent long-term memory: recall, remember, forget, and enable/disable.",
    "members": [
      "std::memory::recall",
      "std::memory::remember",
      "std::memory::forget",
      "std::memory::enableMemory",
      "std::memory::disableMemory"
    ],
    "composedOf": []
  },
  "NotesRead": {
    "name": "NotesRead",
    "doc": "Read-only Notes access: reading, searching, and listing.",
    "members": [
      "std::notes::read",
      "std::notes::search",
      "std::notes::list"
    ],
    "composedOf": []
  },
  "NotesWrite": {
    "name": "NotesWrite",
    "doc": "Notes mutation: creating, appending, and deleting.",
    "members": [
      "std::notes::create",
      "std::notes::append",
      "std::notes::delete"
    ],
    "composedOf": []
  },
  "Notes": {
    "name": "Notes",
    "doc": "All Notes access, reads and writes.",
    "members": [
      "std::notes::read",
      "std::notes::search",
      "std::notes::list",
      "std::notes::create",
      "std::notes::append",
      "std::notes::delete"
    ],
    "composedOf": [
      "NotesRead",
      "NotesWrite"
    ]
  }
};
